services:
  postgres:
    image: postgres:15
    container_name: chat-crm-db_prod
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  api:
    container_name: chat-crm-api_prod
    build:
      context: .
      dockerfile: ./Dockerfile
    command: sh -c "npx prisma migrate deploy && node dist/main.js"
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./gcloud-service-account.json:/usr/src/app/gcloud-service-account.json
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?schema=public
    ports:
      - "${API_PORT}:5000"
    restart: unless-stopped

volumes:
  postgres_data:
