services:
  postgres:
    image: postgres:15
    container_name: chat-crm-db_local
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    container_name: chat-crm-api_local
    build:
      context: .
      dockerfile: ./Dockerfile
    command: sh -c "npx prisma migrate deploy && npm run start:dev"
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?schema=public
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '${API_PORT}:5000'

volumes:
  postgres_data:

